version: '3'

tasks:
  build:
    desc: Build the application
    cmds:
      - echo "Building application..."
      - mkdir -p bin
      - go build -o bin/crypto-converter cmd/main.go
      - echo "Build complete"

  list:
    desc: Show supported currencies
    deps: [build]
    cmds:
      - ./bin/crypto-converter --list

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - go clean

  install:
    desc: Install dependencies
    cmds:
      - go mod download
      - go mod tidy

  setup:
    desc: Setup development environment
    cmds:
      - cp env.example .env
      - echo "Edit .env file with your API key"